# Generated by Django 5.2.10 on 2026-02-17 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyentry',
            name='animal',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='breed',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='phone',
        ),
        migrations.AddField(
            model_name='animal',
            name='milk_per_day',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='salary',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('total_amount', models.FloatField()),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dairy_app.farmer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dairy_app.product')),
            ],
        ),
        migrations.DeleteModel(
            name='Billing',
        ),
        migrations.DeleteModel(
            name='DailyEntry',
        ),
    ]
