# Generated by Django 6.0.2 on 2026-02-19 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dairy_app", "0005_set_admin_password_and_remove_demo"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="phone",
            field=models.CharField(default="", max_length=15),
        ),
    ]
